version: '3.8'

services:
  app:
    build:
      context: .
    container_name: audiotranscriber-app
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    networks:
      - transcriber-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - transcriber-net
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama-data:

networks:
  transcriber-net:
