version: '3.8'

services:
  app:
    build:
      context: .
    container_name: audiotranscriber-app
    ports:
      - "8080:8080"
    networks:
      - transcriber-net

networks:
  transcriber-net:
